### ISSUE TITLE
Compilation Failed on CentOS 7 

### ISSUE THREAD

**Issue by Seeder101** [OlafvdSpek/xbt#59]
Hi Olaf, I just tried installing xbt tracker on a centos 7 minimal installation 
but it keeps failing on the make command with this output 
`[  7%] Building CXX object CMakeFiles/xbt_tracker.dir/root/xbt/misc/bt_misc.cpp.o
In file included from /root/xbt/Tracker/../misc/xbt/data_ref.h:9:0,
                 from /root/xbt/misc/xbt/bt_misc.h:3,
                 from /root/xbt/misc/bt_misc.cpp:1:
/root/xbt/Tracker/../misc/xbt/string_view.h:3:29: fatal error: boost/convert.hpp: No such file or directory
 #include <boost/convert.hpp>
                             ^
compilation terminated.
make[2]: *** [CMakeFiles/xbt_tracker.dir/root/xbt/misc/bt_misc.cpp.o] Error 1
make[1]: *** [CMakeFiles/xbt_tracker.dir/all] Error 2
make: *** [all] Error 2
`

I made sure all deps  are met  but it still keeps failing the cmake works fine but not the make. 
also on centos 7 the gcc version is 4.8 which it's not going to work with xbt so I downloaded a newer version through scl the 8 version but also it didn't work. so I don't know what am actually missing here
EDIT: also the boost version is 1.5.3 so I guess that's sufficient ?
Thank you in advance

**Comment by Seeder101** [comment]
after updating boost to 1.69 I getting the following

`Scanning dependencies of target xbt
[ 20%] Building CXX object CMakeFiles/xbt.dir/bt_misc.cpp.o
In file included from /root/xbt/misc/./xbt/data_ref.h:9,
                 from /root/xbt/misc/xbt/bt_misc.h:3,
                 from /root/xbt/misc/bt_misc.cpp:1:
/root/xbt/misc/./xbt/string_view.h:3:10: fatal error: boost/convert.hpp: No such file or directory
 #include <boost/convert.hpp>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/xbt.dir/bt_misc.cpp.o] Error 1
make[1]: *** [CMakeFiles/xbt.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by Seeder101** [comment]
it seems like there is an issue with the boost library. but I I think that we need more digging to solve the issue probably. what's your main test grond for xbt on linux distros ? are they debian based or rhel ?

**Comment by Seeder101** [comment]
after trying Ubuntu 16.04 it gave me the same exact error 
after trying Debian 9 it didn't give me any errors and compiled successfully. 
so is it the g++ version ? or what exactly ? because in Debian 9 we have g++ version 6.3 
in Ubuntu 16.04 we have 5.3 
if u can try reproduce the issue on a CentOS/Ubuntu 16.04 installation it would be a good idea 

Thank you

**Comment by OlafvdSpek** [comment]
GCC 6 and a recent Boost version are required. The versions in Debian 9 and Ubuntu 18 should be fine.

**Comment by Seeder101** [comment]
> GCC 6 and a recent Boost version are required. The versions in Debian 9 and Ubuntu 18 should be fine. GCC 5 in Ubuntu 16 is too old.

Unfortunately, I couldn't compile xbt even with scl from CentOS as they provide newer version for GCC. I even installed boost 1.69 but still gave me the same so I don't know maybe we should wait until CentOS 8 comes around. I tried compiling your old version from here https://github.com/shakahl/xbt it's a mirrored version of your old code from googlecode, and it worked ok under CentOS 7.

**Comment by OlafvdSpek** [comment]
Why not use Debian 9 or Ubuntu 18?

**Comment by Seeder101** [comment]
> Why not use Debian 9 or Ubuntu 18?

I just want a long LTS based. and CentOS does that for me. I pretty much do everything with CentOS. it's well known for it's long term support over 10 yrs Debian and Ubuntu have 5 years of support which still not that bad and I guess Ubuntu expanded the terms to 10 like RHEL

**Comment by OlafvdSpek** [comment]
Interesting, does the 5 years vs 10 years really make a difference for you?

**Comment by Seeder101** [comment]
> Interesting, does the 5 years vs 10 years really make a difference for you?

yea ofc for big enterprises it does make a different. moving infrastructure and upgrading it requires a bit of more work. when u get LTS support for 10 years you have saved a ton of work.

**Comment by faerot** [comment]
Is there a solution? I am trying to build it on CentOS and:
```
[root@host Tracker]# cmake .
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.7 or higher is required.  You are running version 2.8.12.2
```

**Comment by OlafvdSpek** [comment]
@faerot Upgrade to a distro that provides GCC 6 (and cmake 3.7 if possible).

**Comment by shoaib-125** [comment]
/root/xbt/Tracker/../misc/xbt/string_view.h:3:29: fatal error: boost/convert.hpp: No such file or directory

anyone help to fix this problem on step make
